<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Dinesh" failures="1" tests="8" name="FaliedTC.ng.FailedTestScript" time="0.048" errors="0" timestamp="08 Sep 2020 02:12:03 GMT" skipped="6">
  <testcase classname="FaliedTC.ng.FailedTestScript" name="asserttest2" time="0.004"/>
  <testcase classname="FaliedTC.ng.FailedTestScript" name="asserttest" time="0.000">
    <failure message="The following asserts failed:
	conditionfailed expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
conditionfailed expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at FaliedTC.ng.FailedTestScript.asserttest(FailedTestScript.java:85)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- asserttest -->
  <testcase classname="FaliedTC.ng.FailedTestScript" name="asserttest" time="0.004">
    <skipped/>
  </testcase> <!-- asserttest -->
  <testcase classname="FaliedTC.ng.FailedTestScript" name="asserttest" time="0.016">
    <skipped/>
  </testcase> <!-- asserttest -->
  <testcase classname="FaliedTC.ng.FailedTestScript" name="asserttest" time="0.024">
    <skipped/>
  </testcase> <!-- asserttest -->
  <testcase classname="FaliedTC.ng.FailedTestScript" name="assertDD">
    <skipped/>
  </testcase> <!-- assertDD -->
  <testcase classname="FaliedTC.ng.FailedTestScript" name="SelectvaluefromDD">
    <skipped/>
  </testcase> <!-- SelectvaluefromDD -->
  <testcase classname="FaliedTC.ng.FailedTestScript" name="automationwebsite">
    <skipped/>
  </testcase> <!-- automationwebsite -->
</testsuite> <!-- FaliedTC.ng.FailedTestScript -->
